// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpm6zcJvtnOoE5OOVCEfdcO8yGV65maBg',
    appId: '1:1071651184890:web:6dfae63a7252d88339a943',
    messagingSenderId: '1071651184890',
    projectId: 'rajpoot-foods',
    authDomain: 'rajpoot-foods.firebaseapp.com',
    storageBucket: 'rajpoot-foods.appspot.com',
    measurementId: 'G-8FXTZQVJZ5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBm1heUyXHzVaFoeiBo9T1ikUy74TxN8_4',
    appId: '1:1071651184890:android:a3a3d8068adbd3ef39a943',
    messagingSenderId: '1071651184890',
    projectId: 'rajpoot-foods',
    storageBucket: 'rajpoot-foods.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQPVgUoVH8terHORQOuVGUzlVgJXmc08Q',
    appId: '1:1071651184890:ios:9863b52b2d4ffdfa39a943',
    messagingSenderId: '1071651184890',
    projectId: 'rajpoot-foods',
    storageBucket: 'rajpoot-foods.appspot.com',
    iosBundleId: 'com.example.rajputfoods',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQPVgUoVH8terHORQOuVGUzlVgJXmc08Q',
    appId: '1:1071651184890:ios:9863b52b2d4ffdfa39a943',
    messagingSenderId: '1071651184890',
    projectId: 'rajpoot-foods',
    storageBucket: 'rajpoot-foods.appspot.com',
    iosBundleId: 'com.example.rajputfoods',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDpm6zcJvtnOoE5OOVCEfdcO8yGV65maBg',
    appId: '1:1071651184890:web:a706cd58cb861a0339a943',
    messagingSenderId: '1071651184890',
    projectId: 'rajpoot-foods',
    authDomain: 'rajpoot-foods.firebaseapp.com',
    storageBucket: 'rajpoot-foods.appspot.com',
    measurementId: 'G-TL1EC7J0Y4',
  );
}
